{{- if .Values.collector.node_selector }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: flamegraph-collector
  labels:
    system: flamegraph
    type: worker
spec:
  template:
    metadata:
      labels:
        name: flamegraph-collector
        system: flamegraph
    spec:
      nodeSelector:
        zone: farm
      hostPID: true
      containers:
      - name: pyflame
        image: {{ .Values.images.pyflame }}
        imagePullPolicy: Always
        securityContext:
           privileged: true
        command: ["/usr/local/lib/pyflame/run.py"]
        volumeMounts:
        - mountPath: /usr/local/lib/pyflame
          name: pyflame
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: FLAMEGRAPH_REDIS_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flamegraph-redis
              key: redis-password
      volumes:
      - name: pyflame
        configMap:
          name: flamegraph-collector
          defaultMode: 0755
{{- end }}
